### ISSUE TITLE
Incorrect Cylindrophis melanotus records

### ISSUE THREAD

**Issue by dibamus** [blueraleigh/squamatabase#5]
Four records attributed to Cylindrophis melanotus should instead be attributed to Cylindrophis maculatus, as reported by Greer (1983).
Predator vouchers are:
4ffacf56086d2b0b9e811cb7e3489083
4ac99b621545191e716a82ba490fd1d1
f54a44a4a996be9a908f823515db90eb
2ac628c9d5e1e9dd91b762761a2d4fcd

**Comment by blueraleigh** [comment]
Great catch, thanks!

**Comment by dibamus** [comment]
No problem - caught this while prepping the manuscript for another record.
